### ISSUE TITLE
When cloning Spice, Fatal auth failed from https://forge.siguza.net

### ISSUE THREAD

**Issue by bigrck64** [JakeBlair420/Spice#3]
Hello !

When cloning this repo with
`git clone --recursive --depth=1 git://github.com/JakeBlair420/spice.git`

Git is asking for one password about this submodule
`Submodule 'submodules/libjake' (https://forge.siguza.net/PsychoTea/libjake.git`

It seems fatal for "make" who is generating this error:
`make: *** [libspice.dylib] Error 1`

**Comment by bigrck64** [comment]
Without the "--recursive" git commande, the clone of the repo is correct, but the build of the project is still broken :(

`In file included from src/untether/install.m:8:`
`src/untether/stage2.h:3:10: fatal error: 'img.h' file not found`
`#include "img.h"`
`                ^-------`

**Comment by littlelailo** [comment]
Yes, this is because we have our private offsetfinder on that repo. You can roll back to the commit where everything was working for my iPad in Feb 2019 and then search the symbols manually (might want to look at the current comments in install.m)

**Comment by bigrck64** [comment]
okay, thanks for this information :)
