### ISSUE TITLE
error : 'img.h' file not found

### ISSUE THREAD

**Issue by dbgprud8** [JakeBlair420/Spice#4]
How do I handle the error?
Where did you get this file?

**Comment by Siguza** [comment]
@littlelailo @PsychoTea apparently we didn't push libjake?

**Comment by dbgprud8** [comment]
To use libjake, I need to type username and password, which one should I type in username and password?
Thank you for answering the above questions.

**Comment by Siguza** [comment]
Just pushed. Everything should be fixed now. :)
